image: node:10.14.1

pages:
  stage: deploy
  script:
    - npm config set registry https://registry.npmjs.org/
    - npm i
    - npm run build
    - cd build
    - mv . public
  artifacts:
    paths:
      - public
  only:
  - master